blog_homepage:
    pattern:  /
    defaults: { _controller: BlogBundle:Page:index }
    requirements:
        _method:  GET

BlogBundle_about:
    pattern:  /about
    defaults: { _controller: BlogBundle:Page:about }
    requirements:
        _method:  GET